Repository Pinback-Team/pinback-server, pull requests merged in 2025-07, with the labels that each got.

#4 feat: 도메인 구현
  src/main/java/com/pinback/pinback_server/domain/article/domain/entity/Article.java
  src/main/java/com/pinback/pinback_server/domain/article/domain/repository/ArticleRepository.java
  src/main/java/com/pinback/pinback_server/domain/category/domain/entity/Category.java
  src/main/java/com/pinback/pinback_server/domain/category/domain/repository/CategoryRepository.java
  src/main/java/com/pinback/pinback_server/domain/notification/domain/entity/PushSubscription.java
  src/main/java/com/pinback/pinback_server/domain/notification/domain/repository/PushSubscriptionRepository.java
  src/main/java/com/pinback/pinback_server/domain/user/domain/entity/User.java
  src/main/java/com/pinback/pinback_server/domain/user/domain/repository/UserRepository.java
  src/main/java/com/pinback/pinback_server/global/entity/BaseEntity.java
Labels: feat

#8 feat: 회원가입 기능 구현
  .github/pull_request_template.md
  build.gradle
  src/main/java/com/pinback/pinback_server/domain/auth/application/AuthUsecase.java
  src/main/java/com/pinback/pinback_server/domain/auth/application/command/SignUpCommand.java
  src/main/java/com/pinback/pinback_server/domain/auth/exception/UserDuplicateException.java
  src/main/java/com/pinback/pinback_server/domain/auth/presentation/AuthController.java
  src/main/java/com/pinback/pinback_server/domain/auth/presentation/dto/request/SignUpRequest.java
  src/main/java/com/pinback/pinback_server/domain/auth/presentation/dto/response/SignUpResponse.java
  src/main/java/com/pinback/pinback_server/domain/user/domain/repository/UserRepository.java
  src/main/java/com/pinback/pinback_server/domain/user/domain/service/UserSaveService.java
  src/main/java/com/pinback/pinback_server/domain/user/domain/service/UserValidateService.java
  src/main/java/com/pinback/pinback_server/global/common/jwt/JwtProvider.java
  src/main/java/com/pinback/pinback_server/global/config/cors/CorsConfig.java
  src/main/java/com/pinback/pinback_server/global/config/security/SecurityConfig.java
  src/main/java/com/pinback/pinback_server/global/config/swagger/SwaggerConfig.java
  src/main/java/com/pinback/pinback_server/global/exception/GlobalExceptionHandler.java
  src/main/java/com/pinback/pinback_server/global/exception/constant/ExceptionCode.java
  src/main/resources/application.yml
  src/test/java/com/pinback/pinback_server/domain/auth/application/AuthUsecaseTest.java
  src/test/java/com/pinback/pinback_server/global/common/jwt/JwtProviderTest.java
  src/test/resources/application-test.yml
Labels: feat

#10 feat: 배포 자동화
  .github/workflows/dev.yml
  Dockerfile
  querydsl.gradle
  src/main/resources/application.yml
Labels: feat

#11 feat: 인증 인가 설정
  src/main/java/com/pinback/pinback_server/domain/user/domain/service/UserGetService.java
  src/main/java/com/pinback/pinback_server/domain/user/exception/UserNotFoundException.java
  src/main/java/com/pinback/pinback_server/global/common/annotation/CurrentUser.java
  src/main/java/com/pinback/pinback_server/global/common/jwt/JwtUtil.java
  src/main/java/com/pinback/pinback_server/global/common/jwt/exception/ExpiredTokenException.java
  src/main/java/com/pinback/pinback_server/global/common/jwt/exception/InvalidTokenException.java
  src/main/java/com/pinback/pinback_server/global/config/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/pinback/pinback_server/global/config/mvc/WebMvcConfig.java
  src/main/java/com/pinback/pinback_server/global/config/resolver/CurrentUserArgumentResolver.java
  src/main/java/com/pinback/pinback_server/global/config/security/SecurityConfig.java
  src/main/java/com/pinback/pinback_server/global/config/swagger/SwaggerConfig.java
  src/main/java/com/pinback/pinback_server/global/exception/constant/ExceptionCode.java
  src/test/java/com/pinback/pinback_server/domain/auth/application/AuthUsecaseTest.java
  src/test/java/com/pinback/pinback_server/global/common/jwt/JwtUtilTest.java
Labels: feat

#16 feat: 아티클 생성로직 구현
  src/main/java/com/pinback/pinback_server/domain/article/application/ArticleManagementUsecase.java
  src/main/java/com/pinback/pinback_server/domain/article/application/command/ArticleCreateCommand.java
  src/main/java/com/pinback/pinback_server/domain/article/domain/entity/Article.java
  src/main/java/com/pinback/pinback_server/domain/article/domain/repository/ArticleRepository.java
  src/main/java/com/pinback/pinback_server/domain/article/domain/service/ArticleGetService.java
  src/main/java/com/pinback/pinback_server/domain/article/domain/service/ArticleSaveService.java
  src/main/java/com/pinback/pinback_server/domain/article/exception/ArticleAlreadyExistException.java
  src/main/java/com/pinback/pinback_server/domain/article/presentation/ArticleController.java
  src/main/java/com/pinback/pinback_server/domain/article/presentation/dto/request/ArticleCreateRequest.java
  src/main/java/com/pinback/pinback_server/domain/category/domain/repository/CategoryRepository.java
  src/main/java/com/pinback/pinback_server/domain/category/domain/service/CategoryGetService.java
  src/main/java/com/pinback/pinback_server/domain/category/exception/CategoryNotFoundException.java
  src/main/java/com/pinback/pinback_server/global/exception/constant/ExceptionCode.java
  src/test/java/com/pinback/pinback_server/domain/ApplicationTest.java
  src/test/java/com/pinback/pinback_server/domain/article/application/ArticleManagementUsecaseTest.java
  src/test/java/com/pinback/pinback_server/domain/category/domain/service/CategoryGetServiceTest.java
  src/test/java/com/pinback/pinback_server/domain/fixture/CustomRepository.java
  src/test/java/com/pinback/pinback_server/domain/fixture/TestFixture.java
Labels: feat

#22 feat: 아티클 전체 조회 구현
  src/main/java/com/pinback/pinback_server/domain/article/application/ArticleManagementUsecase.java
  src/main/java/com/pinback/pinback_server/domain/article/domain/repository/ArticleRepository.java
  src/main/java/com/pinback/pinback_server/domain/article/domain/repository/ArticleRepositoryCustom.java
  src/main/java/com/pinback/pinback_server/domain/article/domain/repository/ArticleRepositoryCustomImpl.java
  src/main/java/com/pinback/pinback_server/domain/article/domain/service/ArticleGetService.java
  src/main/java/com/pinback/pinback_server/domain/article/presentation/ArticleController.java
  src/main/java/com/pinback/pinback_server/domain/article/presentation/dto/response/ArticleAllResponse.java
  src/main/java/com/pinback/pinback_server/domain/article/presentation/dto/response/ArticlesResponse.java
  src/main/java/com/pinback/pinback_server/global/config/swagger/SwaggerConfig.java
  src/test/java/com/pinback/pinback_server/domain/article/application/ArticleManagementUsecaseTest.java
  src/test/java/com/pinback/pinback_server/domain/fixture/TestFixture.java
Labels: feat

#27 feat: 아티클 카테고리 조회 구현
  src/main/java/com/pinback/pinback_server/domain/article/application/ArticleManagementUsecase.java
  src/main/java/com/pinback/pinback_server/domain/article/domain/entity/Article.java
  src/main/java/com/pinback/pinback_server/domain/article/domain/repository/ArticleRepositoryCustom.java
  src/main/java/com/pinback/pinback_server/domain/article/domain/repository/ArticleRepositoryCustomImpl.java
  src/main/java/com/pinback/pinback_server/domain/article/domain/repository/dto/ArticlesWithUnreadCount.java
  src/main/java/com/pinback/pinback_server/domain/article/domain/service/ArticleGetService.java
  src/main/java/com/pinback/pinback_server/domain/article/presentation/ArticleController.java
  src/main/java/com/pinback/pinback_server/domain/article/presentation/dto/response/ArticleAllResponse.java
  src/main/java/com/pinback/pinback_server/domain/article/presentation/dto/response/ArticlesResponse.java
  src/test/java/com/pinback/pinback_server/domain/article/application/ArticleManagementUsecaseTest.java
  src/test/java/com/pinback/pinback_server/domain/fixture/TestFixture.java
Labels: feat

#30 fix: soft delete 삭제
  src/main/java/com/pinback/pinback_server/domain/article/domain/repository/ArticleRepositoryCustomImpl.java
  src/main/java/com/pinback/pinback_server/global/entity/BaseEntity.java
Labels: feat

#31 feat: 카테고리 전체 조회 구현
  src/main/java/com/pinback/pinback_server/domain/article/domain/repository/ArticleRepository.java
  src/main/java/com/pinback/pinback_server/domain/article/domain/service/ArticleGetService.java
  src/main/java/com/pinback/pinback_server/domain/category/application/CategoryManagementUsecase.java
  src/main/java/com/pinback/pinback_server/domain/category/domain/repository/CategoryRepository.java
  src/main/java/com/pinback/pinback_server/domain/category/domain/repository/CategoryRepositoryCustom.java
  src/main/java/com/pinback/pinback_server/domain/category/domain/repository/CategoryRepositoryCustomImpl.java
  src/main/java/com/pinback/pinback_server/domain/category/domain/repository/dto/CategoriesForDashboard.java
  src/main/java/com/pinback/pinback_server/domain/category/domain/repository/dto/CategoriesForExtension.java
  src/main/java/com/pinback/pinback_server/domain/category/domain/repository/dto/CategoryForDashboard.java
  src/main/java/com/pinback/pinback_server/domain/category/domain/service/CategoryGetService.java
  src/main/java/com/pinback/pinback_server/domain/category/presentation/CategoryController.java
  src/main/java/com/pinback/pinback_server/domain/category/presentation/dto/response/CategoryAllDashboardResponse.java
  src/main/java/com/pinback/pinback_server/domain/category/presentation/dto/response/CategoryAllExtensionResponse.java
  src/main/java/com/pinback/pinback_server/domain/category/presentation/dto/response/CategoryDashboardResponse.java
  src/main/java/com/pinback/pinback_server/domain/category/presentation/dto/response/CategoryExtensionResponse.java
Labels: feat

#38 feat: 카테고리 수정 기능 구현
  src/main/java/com/pinback/pinback_server/domain/category/application/CategoryManagementUsecase.java
  src/main/java/com/pinback/pinback_server/domain/category/application/command/CategoryUpdateCommand.java
  src/main/java/com/pinback/pinback_server/domain/category/domain/entity/Category.java
  src/main/java/com/pinback/pinback_server/domain/category/presentation/CategoryController.java
  src/main/java/com/pinback/pinback_server/domain/category/presentation/dto/request/CategoryUpdateRequest.java
  src/main/java/com/pinback/pinback_server/domain/category/presentation/dto/response/UpdateCategoryResponse.java
Labels: feat

#44 refactor: 예외코드 중복 수정
  src/main/java/com/pinback/pinback_server/global/exception/constant/ExceptionCode.java
Labels: refactor

#46 fix: 리마인드 조회 응답 수정 및 아티클 생성 글자수 예외 추가
  src/main/java/com/pinback/pinback_server/domain/article/application/ArticleManagementUsecase.java
  src/main/java/com/pinback/pinback_server/domain/article/exception/MemoLengthLimitException.java
  src/main/java/com/pinback/pinback_server/domain/article/presentation/dto/response/RemindArticleResponse.java
  src/main/java/com/pinback/pinback_server/domain/article/presentation/dto/response/RemindArticles.java
  src/test/java/com/pinback/pinback_server/domain/article/application/ArticleRemindTest.java
Labels: bug, refactor

#49 feat: redis config 추가
  .github/workflows/dev.yml
  src/main/java/com/pinback/pinback_server/global/config/redis/RedisConfig.java
  src/test/java/com/pinback/pinback_server/global/config/redis/TestRedisConfig.java
  src/test/resources/application-test.properties
Labels: feat

#51 feat: 아티클 읽음 표시 변경 기능 구현
  docker-compose.yml
  src/main/java/com/pinback/pinback_server/domain/article/application/ArticleManagementUsecase.java
  src/main/java/com/pinback/pinback_server/domain/article/domain/repository/ArticleRepository.java
  src/main/java/com/pinback/pinback_server/domain/article/domain/service/ArticleGetService.java
  src/main/java/com/pinback/pinback_server/domain/article/presentation/ArticleController.java
  src/main/java/com/pinback/pinback_server/domain/article/presentation/dto/response/ReadArticleResponse.java
  src/main/java/com/pinback/pinback_server/infra/redis/AcornService.java
  src/main/java/com/pinback/pinback_server/infra/redis/dto/response/AcornCollectResponse.java
Labels: feat

#53 feat: 유저 도토리 정보 조회 기능 구현
  src/main/java/com/pinback/pinback_server/domain/user/application/UserManagementUsecase.java
  src/main/java/com/pinback/pinback_server/domain/user/exception/UserNotFoundException.java
  src/main/java/com/pinback/pinback_server/domain/user/presentation/UserController.java
  src/main/java/com/pinback/pinback_server/domain/user/presentation/dto/response/UserInfoResponse.java
Labels: feat

#54 feat: 리마인드 알림 기능 구현
  build.gradle
  src/main/java/com/pinback/pinback_server/domain/article/application/ArticleManagementUsecase.java
  src/main/java/com/pinback/pinback_server/domain/article/domain/service/ArticleSaveService.java
  src/main/java/com/pinback/pinback_server/domain/auth/application/AuthUsecase.java
  src/main/java/com/pinback/pinback_server/domain/auth/application/command/SignUpCommand.java
  src/main/java/com/pinback/pinback_server/domain/auth/presentation/dto/request/KeyCommand.java
  src/main/java/com/pinback/pinback_server/domain/auth/presentation/dto/request/NotificationInfoCommand.java
  src/main/java/com/pinback/pinback_server/domain/auth/presentation/dto/request/SignUpRequest.java
  src/main/java/com/pinback/pinback_server/domain/notification/domain/entity/PushSubscription.java
  src/main/java/com/pinback/pinback_server/domain/notification/domain/repository/PushSubscriptionRepository.java
  src/main/java/com/pinback/pinback_server/domain/notification/domain/service/PushSubscriptionGetService.java
  src/main/java/com/pinback/pinback_server/domain/notification/domain/service/PushSubscriptionSaveService.java
  src/main/java/com/pinback/pinback_server/domain/notification/exception/SubscriptionNotFoundException.java
  src/main/java/com/pinback/pinback_server/domain/notification/presentation/dto/request/KeyRequest.java
  src/main/java/com/pinback/pinback_server/domain/notification/presentation/dto/request/NotificationOnboardingRequest.java
  src/main/java/com/pinback/pinback_server/global/common/util/TextUtil.java
  src/main/java/com/pinback/pinback_server/global/config/firebase/FirebaseConfig.java
  src/main/java/com/pinback/pinback_server/global/config/redis/RedisConfig.java
  src/main/java/com/pinback/pinback_server/global/exception/constant/ExceptionCode.java
  src/main/java/com/pinback/pinback_server/infra/firebase/FcmService.java
  src/main/java/com/pinback/pinback_server/infra/redis/NotificationExpirationListener.java
  src/main/java/com/pinback/pinback_server/infra/redis/dto/NotificationData.java
  src/main/java/com/pinback/pinback_server/infra/redis/service/RedisNotificationService.java
  src/main/resources/application.yml
  src/test/java/com/pinback/pinback_server/domain/article/application/ArticleManagementUsecaseTest.java
  src/test/java/com/pinback/pinback_server/domain/auth/application/AuthUsecaseTest.java
  src/test/resources/application-test.properties
Labels: feat

#57 feat: 아티클 수정기능 구현
  .gitignore
  docker-compose.yml
  src/main/java/com/pinback/pinback_server/domain/article/application/ArticleManagementUsecase.java
  src/main/java/com/pinback/pinback_server/domain/article/application/command/ArticleUpdateCommand.java
  src/main/java/com/pinback/pinback_server/domain/article/domain/entity/Article.java
  src/main/java/com/pinback/pinback_server/domain/article/presentation/ArticleController.java
  src/main/java/com/pinback/pinback_server/domain/article/presentation/dto/request/ArticleUpdateRequest.java
Labels: feat

#62 feat: 유저 기본 리마인드 시간 조회 기능 구현
  src/main/java/com/pinback/pinback_server/domain/user/application/UserManagementUsecase.java
  src/main/java/com/pinback/pinback_server/domain/user/presentation/UserController.java
  src/main/java/com/pinback/pinback_server/domain/user/presentation/dto/response/UserRemindInfoResponse.java
Labels: feat

#65 feat: 유저 도토리 조회 시 리마인드 시간 타입 변경
  src/main/java/com/pinback/pinback_server/domain/user/application/UserManagementUsecase.java
  src/main/java/com/pinback/pinback_server/domain/user/presentation/dto/response/UserInfoResponse.java
Labels: FEAT

#70 refactor: 카테고리 생성/수정 응답 DTO 필드명 변경
  src/main/java/com/pinback/pinback_server/domain/category/presentation/dto/response/CreateCategoryResponse.java
  src/main/java/com/pinback/pinback_server/domain/category/presentation/dto/response/UpdateCategoryResponse.java
Labels: REFACTOR

#73 feat: 안읽은 아티클 조회 기능 구현
  src/main/java/com/pinback/pinback_server/domain/article/application/ArticleManagementUsecase.java
  src/main/java/com/pinback/pinback_server/domain/article/domain/repository/ArticleRepositoryCustom.java
  src/main/java/com/pinback/pinback_server/domain/article/domain/repository/ArticleRepositoryCustomImpl.java
  src/main/java/com/pinback/pinback_server/domain/article/domain/service/ArticleGetService.java
  src/main/java/com/pinback/pinback_server/domain/article/presentation/ArticleController.java
  src/main/java/com/pinback/pinback_server/domain/article/presentation/dto/response/ArticleUnreadResponse.java
Labels: FEAT

#76 feat: 카테고리 생성 테스트 API 구현
  src/main/java/com/pinback/pinback_server/domain/test/application/TestUsecase.java
  src/main/java/com/pinback/pinback_server/domain/test/presentation/TestController.java
  src/main/java/com/pinback/pinback_server/domain/test/presentation/dto/response/CategoriesTestResponse.java
Labels: FEAT

#78 feat: 아티클 목업 데이터 생성 로직 구현
  src/main/java/com/pinback/pinback_server/domain/notification/domain/entity/PushSubscription.java
  src/main/java/com/pinback/pinback_server/domain/test/application/TestUsecase.java
  src/main/java/com/pinback/pinback_server/domain/test/presentation/TestController.java
Labels: FEAT

#82 fix: 카테고리 삭제 시 아티클도 함께 삭제되도록 기능 수정
  src/main/java/com/pinback/pinback_server/domain/article/domain/repository/ArticleRepository.java
  src/main/java/com/pinback/pinback_server/domain/article/domain/repository/ArticleRepositoryCustom.java
  src/main/java/com/pinback/pinback_server/domain/article/domain/repository/ArticleRepositoryCustomImpl.java
  src/main/java/com/pinback/pinback_server/domain/article/domain/service/ArticleDeleteService.java
  src/main/java/com/pinback/pinback_server/domain/category/application/CategoryManagementUsecase.java
  src/main/java/com/pinback/pinback_server/domain/test/application/TestUsecase.java
Labels: FIX
